# Generated by Django 6.0 on 2025-12-04 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100)),
                ('tipo_planta', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('previsao_colheita', models.DateField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em manutenção'), ('colhido', 'Colhido')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_familia', models.CharField(max_length=200)),
                ('representante', models.CharField(max_length=200)),
                ('integrantes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mutirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('atividades', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField()),
                ('quantidade', models.FloatField()),
                ('unidade', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('canteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cor.canteiro')),
            ],
        ),
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.FloatField()),
                ('unidade', models.CharField(max_length=20)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cor.familia')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cor.producao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('voluntario', 'Voluntário')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresencaMutirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, max_length=100)),
                ('mutirao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cor.mutirao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cor.usuario')),
            ],
        ),
    ]
